steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west9-docker.pkg.dev/${PROJECT_ID}/dbt-registry/dbt-project', 
           '.']
images: [ 'europe-west9-docker.pkg.dev/${PROJECT_ID}/dbt-registry/dbt-project' ]

  # # Docker Push
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 
  #          'europe-west9-docker.pkg.dev/${PROJECT_ID}/dbt-registry/dbt-project']

  #   # Deploy Cloud Run
  # - name: 'google/cloud-sdk:429.0.0'
  #   args:
  #     - 'gcloud'
  #     - 'run'
  #     - 'deploy'
  #     - 'dbt-project'
  #     - '--image'
  #     - 'europe-west9-docker.pkg.dev/${PROJECT_ID}/dbt-registry/dbt-project:latest'
  #     - '--region'
  #     - 'europe-west1'
  #     - '--allow-unauthenticated'
  
  # # Build cloud run
  # - name: google/cloud-sdk:429.0.0
  #   args: ['./script/deploy-cloud-run.sh']
  #   env:
  #     - 'SERVICE_NAME=$_SERVICE_NAME'
  
# substitutions:
#   _SERVICE_NAME: $SERVICE_NAME 