steps:
  # Étape 1 : Construire une image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9.pkg.dev/$PROJECT_ID/dbt-registry/dbt-project:$COMMIT_SHA', '.']
    #args: ['build', '-t', 'europe-west9-docker.pkg.dev/$PROJECT_ID/dbt-registry/dbt-project:tag2', '.']

  # Étape 2 : Pousser l'image dans Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/$PROJECT_ID/dbt-registry/dbt-project:$COMMIT_SHA']
    #args: ['push', 'europe-west9-docker.pkg.dev/$PROJECT_ID/dbt-registry/dbt-project:tag2']
logsBucket: gs://dbt-logs