name: "dbt_workflow_dkt"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_workflow_dkt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_workflow_dkt:
    bronze:
      +materialized: view
    silver:
      +schema: silver_dbt_workflow
      +materialized: table
    gold:
      +schema: gold_dbt_workflow
      +materialized: view
