[tool.poetry]
name = "dbt-workflow-dkt"
version = "1.2.0"
description = ""
authors = ["wilfried <wilfried.tayo@groupe-esigelec.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dbt-core = "^1.8.9"
dbt-bigquery = "^1.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
